"""empty message

Revision ID: 3401e6de24f6
Revises: 79964a0c5159
Create Date: 2021-08-26 18:58:50.210239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3401e6de24f6'
down_revision = '79964a0c5159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'num_upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shows', 'num_past_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'num_past_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows', 'num_upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
