"""empty message

Revision ID: 02d68653e711
Revises: ad23785e1ee4
Create Date: 2021-08-26 16:23:16.731369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d68653e711'
down_revision = 'ad23785e1ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Venue_phone_key', 'Venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Venue_phone_key', 'Venue', ['phone'])
    # ### end Alembic commands ###
